### ISSUE TITLE
Reflec Beat Volzza 2 should be treated as a expansion.

### ISSUE THREAD

**Issue by maspling** [DragonMinded/bemapi#2]
Since internally Reflec Beat Volzza 2 is treated as the fifth version of the game (player5 etc.) while Reflec Beat Reflesia is treated as the sixth version of the game (boot say reflec6, endpoints player6) it is strange to call it version 7 in the api.  It would be better to treat it as an append version.

"6" -> "5a" / "5_2" / "5t"
"7" -> "6"

**Comment by DragonMinded** [comment]
This seems more correct, actually. I'm a bit worried about how to make the change. I guess I could bump the version number and change that, because it would be a breaking change for existing API clients/servers. Let me mull it over.

**Comment by DragonMinded** [comment]
Given that there aren't any other implementations of this aside from my own network code, I think I'm going to just update the spec to reflect this. Closing and will update spec soonish.
