### ISSUE TITLE
Jubeat excellent clear should be named `exc`

### ISSUE THREAD

**Issue by mbilker** [DragonMinded/bemapi#3]
I was reading through the specification and noticed that jubeat has an excellent clear listed as `ec` rather than the more common representation `exc`.

Could the specification be changed to use `exc` instead?
I do understand that this may not be feasible considering the implementations of the specification on existing servers.

**Comment by DragonMinded** [comment]
This is possible. Servers should not expose internal implementation details, so a rename like this is doable. I'll get to it soon.

**Comment by mbilker** [comment]
It's not really an internal implementation detail more as changing the name to match the more common representation that is even used in game, but, in practice, the implementation depends on the server.

**Comment by DragonMinded** [comment]
Okay, pushed the update. Sorry for the delay!
